.TH zns.fibmap 8

.SH NAME
zns.fibmap \- Identifying File System Extent Mapping on ZNS Devices with \fIFIBMAP\fP

.SH SYNOPSIS
.B zns.fibmap
[
.B \-h
.I show help menu
]
[
.B \-l
.I show \fIFIBMAP\fP flags with extents
]
[
.B \-s
.I show holes between extents
]
[
.B \-w 
.I show \fIFIBMAP\fP extent flags
]
[
.B \-l [Int]
.I logging level for output
]
.B \-f [File]
.I path to the file to be mapped

.SH DESCRIPTION
is used for identifying the file system usage of ZNS devices by locating extents, contiguous regions of file data, on the ZNS device, and showing the fragmentation of file data over the zones. It locates the physical block address (\fIPBA\fP) ranges and zones in which files are located on \fIZNS\fP devices, listing the specific ranges of \fIPBAs\fP and which zones these are in. 

.SH OPTIONS
.BI \-h " show help menu"
Show the help menu and acronym information.
.TP
.BI \-s " show holes"
Show holes between the different extents.
.BI \-l " logging level for output"
Set the logging level for output messages. 0 by default. 1 for more verbose logging.
.TP
.BI \-w " show \fIFIBMAP\fP extent flags"
Show the flags of extents returned by \fIioctl()\fP with \fIFIBMAP\fP.
.TP
.TP
.BI \-f " file to be mapped"
Argument with the file path of the to be mapped file.

.SH OUTPUT
.B zns.fibmap
outputs which zones contain what extents. For convenience we include zone information in the output, such as the starting and ending addresses, such that it is easier to understand if the file is occupying the entire zone or only parts. The important information is the range of the block addresses, which we depict with a start and ending address of the extent. The output contains several acronyms:
.TP

.BI LBAS
Logical Block Address Start (for the Zone)
.TP
.BI LBAE
Logical Block Address End (for the Zone, equal to LBAS + ZONE CAP)
.TP
.BI CAP
Zone Capacity (in 512B sectors)
.TP
.BI WP
Write Pointer of the Zone
.TP
.BI SIZE
Size of the Zone (in 512B sectors)
.TP
.BI STATE
State of a zone
.TP
.BI MASK
The Zone Mask that is used to calculate LBAS of LBA addresses in a zone
.TP
.BI EXTID
Extent number in the order of the extents returned by ioctl(), depciting logical file data ordering
.TP
.BI PBAS
Physical Block Address Start
.TP
.BI PBAE
Physical Block Address End 
.TP
.BI FLAGS
Flags of the extent as returned by ioctl()
.TP
.BI NOE
Number of Extents
.TP
.BI NOZ
Number of Zones (in which extents are)
.TP
.BI TES
Total Extent Size (in 512B sectors)
.TP
.BI AES
Average Extent Size (floored value due to hex print, in 512B sectors). Meant for easier comparison with Extent Sizes.
.TP
.BI EAES
Exact Average Extent Size (double point precision value, in 512B sectors). Meant for exact calculations of average extent sizes.
.TP
.BI NOH
Number of Holes
.TP
.BI THS
Total Hole Size (in 512B sectors)
.TP
.BI AHS
Average Hole Size (floored value due to hex print, in 512B sectors). Meant for easier comparison with Extent Sizes.
.TP
.BI EAHS
Exact Average Hole Size (double point precision value, in 512B sectors). Meant for exact calculations of average hole sizes.

.SH Limitations
F2FS utilizes all devices (zoned and conventional) as one address space, hence extent mappings return offsets in this range. This requires to subtract the conventional device size from offsets to get the location on the ZNS. Therefore, the utility only works with a single ZNS device currently, and relies on the address space being conventional followed by ZNS (which is how F2FS handles it anyways). 
.TP
F2FS also does not directly tell us which devices it is using. If we have a setup with a conventional device and a ZNS, it is mounted as the ZNS device, and \fIioctl()\fP stat calls on all files return the conventional space device ID. Therefore, we cannot easily know which ZNS device it is actually using. The only place currently is the Kernel Log, however it's too cumbersome to parse all this, and there must be better ways. Therefore, program will currently ask the user for the associated ZNS devices.
.TP
Extents that are out of the address range for the ZNS device are not included in the statistics (e.g., when F2FS uses inline data the extent is not on the ZNS but the conventional block device). We still show a warning about such as extents and their info.

.SH AUTHORS
The code was written by Nick Tehrany <tehrany.nick@gmail.com>.

.SH AVAILABILITY
.B zns.fibmap
is available from https://github.com/nicktehrany/zns-tools.git

.SH SEE ALSO
.BR zns.segmap(8)
