.TH zns.segmap 8

.SH NAME
zns.segmap \- The the F2FS segment layout over the zones on ZNS Devices for all files at the mountpoint





.SH AUTHORS
The code was written by Nick Tehrany <nicktehrany1@gmail.com>.

.SH AVAILABILITY
.B zns.segmap
is available from https://github.com/nicktehrany/zns-tools.git

.SH SEE ALSO
.BR zns.fibmap(8)
