#! /bin/bash

set -e

DEV="nvme0n2"
DATA_DIR="zns_single_zone_iodepth"
IODEPTH=(1 2 4 8 16 32 64 128 256 512 1028)

echo mq-deadline | sudo tee /sys/block/${DEV}/queue/scheduler > /dev/null

mkdir -p $DATA_DIR

for iodepth in ${IODEPTH[@]}; do
    echo "Running benchmark with 1 zone iodepth: ${iodepth}"
    sudo nvme zns reset-zone -a /dev/${DEV}

    sudo ${FIO_HOME}/fio --name=zns-single_zone --filename=/dev/${DEV} --size=20z --ioengine=io_uring --fixedbufs=1 --registerfiles=1 --hipri=1 --sqthread_poll=2 --iodepth=${iodepth} --rw=write --bs=4K --direct=1 --zonemode=zbd --runtime=30s --numjobs=1 --offset_increment=20z --max_open_zones=14 --group_reporting --thread=1 --ramp_time=10s --output=${DATA_DIR}/zns_single_zone_iodepth-${iodepth}.json --output-format=json --ioscheduler=mq-deadline

done

DATA_DIR="zns_two_zone_iodepth"
mkdir -p $DATA_DIR

for iodepth in ${IODEPTH[@]}; do
    echo "Running benchmark with 2 zones iodepth: ${iodepth}"
    sudo nvme zns reset-zone -a /dev/${DEV}

    sudo ${FIO_HOME}/fio --name=zns-two_zone --filename=/dev/${DEV} --size=20z --ioengine=io_uring --fixedbufs=1 --registerfiles=1 --hipri=1 --sqthread_poll=2 --iodepth=${iodepth} --rw=write --bs=4K --direct=1 --zonemode=zbd --runtime=30s --numjobs=2 --offset_increment=20z --max_open_zones=14 --group_reporting --thread=2 --ramp_time=10s --output=${DATA_DIR}/zns_two_zone_iodepth-${iodepth}.json --output-format=json --ioscheduler=mq-deadline

done

DATA_DIR="zns_three_zone_iodepth"
mkdir -p $DATA_DIR

for iodepth in ${IODEPTH[@]}; do
    echo "Running benchmark with 3 zones iodepth: ${iodepth}"
    sudo nvme zns reset-zone -a /dev/${DEV}

    sudo ${FIO_HOME}/fio --name=zns-three_zone --filename=/dev/${DEV} --size=20z --ioengine=io_uring --fixedbufs=1 --registerfiles=1 --hipri=1 --sqthread_poll=2 --iodepth=${iodepth} --rw=write --bs=4K --direct=1 --zonemode=zbd --runtime=30s --numjobs=3 --offset_increment=20z --max_open_zones=14 --group_reporting --thread=3 --ramp_time=10s --output=${DATA_DIR}/zns_two_zone_iodepth-${iodepth}.json --output-format=json --ioscheduler=mq-deadline

done
