#! /bin/bash

set -e

DATA_DIR="f2fs_single_stream_iodepth"
DEV="nvme0n1"
ZNS="nvme0n2"
IODEPTH=($(seq 1 1 8))

mkdir -p $DATA_DIR

for iodepth in ${IODEPTH[@]}; do
    echo "Running benchmark with iodepth: ${iodepth}"
    ../setup_f2fs ${ZNS} ${DEV}

    sudo ${FIO_HOME}/fio --name=zns-fio --directory=/mnt/f2fs --size=10G --ioengine=libaio --iodepth=${iodepth} --rw=write --bs=4K --runtime=30s --numjobs=1 --ramp_time=10s --output=${DATA_DIR}/f2fs_iodepth-${iodepth}.json --output-format=json --write_hint=short --nrfiles=1 --thread=1
done
